services:
  - type: worker
    name: devman-review-alert
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DEVMAN_TOKEN
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
